### ISSUE TITLE
Bug in Run-Install?

### ISSUE THREAD

**Issue by JasonCarter80** [JasonCarter80/sqlspade#10]
<b>ChrisAllenNC[CodePlex]</b> <br />I believe there's a bug in the Run-Install.ps1 file, the block starts at line 250.
# Use default instance if none is provided
# if ($instanceName -eq quotquot)

{
     $instanceName -eq quotMSSQLSERVERquot
}
Should it not be:
# Use default instance if none is provided

if ($instanceName -eq quotquot)
{
     $instanceName = quotMSSQLSERVERquot
}
Seeing that block doesn't do anything other than a comparison, when I believe that it would be planned to do an assignment. I first thought about this when I kept seeing False or True at the top of the console for no reason whenever I executed.

**Comment by JasonCarter80** [comment]
<b>Dready[CodePlex]</b> <br />Hi sarasotasql

First of all, thanks for your great work

Just have one question : 
Actual release is SPADE 1.3 dated of Oct 16, 2013.
I have seen that this bug is UPDATED ON::Dec 20, 2013 at 9:39 PM, so is there any chance to see SPADE 1.4 ?

is it still maintained ?

Thanks in advance for your reply

**Comment by JasonCarter80** [comment]
<b>sarasotasql[CodePlex]</b> <br />You are absolutely right...I'll make the change and add it for the next release.

Thank you for that great catch.

**Comment by gbuczylowski** [comment]
I believe the issue was fixed, but there is a new issue (#25  ) with the same code section. 
'execute post-install checklist' section expects $Parameters.InstanceName, but the parameter is not being parsed from parameters hash table.

$IsSysAdmin = Execute-SqlScalarQuery -sqlScript "select is_srvrolemember('sysadmin')" -sqlInstance $Parameters.InstanceName
