### ISSUE TITLE
Newbie Questions

### ISSUE THREAD

**Issue by goforebroke** [JasonCarter80/sqlspade#21]
Have a few questions about your project now that I read through the documentation. Just need a little clarification...

1. <Setting Name="INSTALLSQLDATADIR"> Does this mean that the system databases are installed on the same drive as the SharedDir and InstanceDir Values?

INSTALLSHAREDDIR:              
INSTANCEDIR:

Do I have to add these to the script?

2.  The datacenter tag
    DataCenter Name="Data Center 1" Location="Location 1" FilePath="\\someserver\someshare\MSSQL" 

So this is a path to the SQL Installation files on some network share? So this is updated each time I do an install to point to the correct version for install?

3. Where are the SQL install files copied to? 

4.  SPADE can be run from a central server???

**Comment by JasonCarter80** [comment]
1.  Those locations are for the binary installs, not your data.  Alot of folks put those in the default C:\Program Files directory
2. The data center tag tells the scripts where to find the source files.   Generally, you keep all your SPADE files on a file share somewhere, copy just the  Start-SqlSpade.ps1, Run-Install.config and Run-Install.ps1 to your local computer and execute the Start-SqlSpade.ps1, that script will execute the Run-Install with all the values you set, which then copies everything else from the DataCenter FilePath location.    As part of the config you will also set the Version and Edition,   if you look at those sections in the Config file you will see Edition FolderName,  both the FilePath + FolderName will get combined to figure out the path to the proper set of installers.   Copy-InstallFile.ps1 is the file that copies the actual binaries.
3.   This value is set in the Config file  FilePath variable.   Usually, I create this folder, copy the above three files there and execute them from there.
4.   It cannot be run as a push from a central server.  You will need to be on the server to which you want SQL installed.  I am working (slowly) through an automated routine to execute SQLSpade by way of Chef, so that it could be automated through enterprise automation tools, but that is yet to be completed as of yet.

**Comment by goforebroke** [comment]
Thx for your responses... I meant to say I am new to SPADE not database administration...

So the Data Center location is where your source the SPADE files except for "Start-SqlSpade.ps1", "Run-Install.config" and "Run-Install.ps1", which are copied and run from the server that will do the install. 

I have copied the spade files to a central share and copied the 3 files above to the server where I will perform my install. The problem is it looks for the SQL Installation files under the same folder as the SPADE sources files. If I place all my SQL Installations (2012, 2014 etc..) under the same folder as SPADE, not only does the installer copy all the SPADE source files, but all the editions of SQL including the version specified in "Start-SqlSpade.ps1". I thought the SQL Files could be in a separate path from the SPADE files? 

What am I missing?

Thank you

**Comment by goforebroke** [comment]
I see the binary path... I added that to my first data center location ...It found the right version...

**Comment by goforebroke** [comment]
Hi Jason,

This is really a great tool. I have been stepping through the code trying to understand all the steps and dependencies. I have used the simulation parameter (very useful) so I can read the log files and see how the config file is built and where/how the files get copied....

 Is there any flexibility to tell the  the installer where to copy the SP's and CU's? It appears to default to the Spade source file location and appending the SQLVersion and "Update" based on the robocopy logs..

eg \\PathToSpadeSourceFiles\SQL2014\Updates

**Comment by goforebroke** [comment]
I found where I could update the code to suit my environment in Copy-InstallFiles.ps1 for updates..
I changed the $copyUpdates variable from $Global:SourcePath + $sqlVersion + '\Updates' to $Global:BinariesPath + $sqlVersion + '\Updates'
